import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'firebase_options.dart';

Future<void> main() async {
  // Required to talk to the native Android platform
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase using the file generated by FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const NeonXOXApp());
}

class NeonXOXApp extends StatelessWidget {
  const NeonXOXApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Neon XOX Deluxe',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF0D0D0D), // Dark OLED Black
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.cyan,
          brightness: Brightness.dark,
          primary: Colors.cyanAccent,
          secondary: Colors.pinkAccent,
        ),
      ),
      home: const ConnectionCheckScreen(),
    );
  }
}

class ConnectionCheckScreen extends StatelessWidget {
  const ConnectionCheckScreen({super.key});

  // Function to test the Firebase "Ping"
  Future<void> _pingFirebase(BuildContext context) async {
    try {
      // 1. Reference the 'status' node in Realtime Database
      final DatabaseReference dbRef = FirebaseDatabase.instance.ref("connection_test");

      // 2. Write test data with a Server Timestamp
      await dbRef.set({
        "status": "Neon XOX Online!",
        "device": "Physical Device",
        "last_ping": ServerValue.timestamp,
      });

      // 3. Show success message
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("🚀 Firebase Connected! Data written successfully."),
            backgroundColor: Colors.cyanAccent,
          ),
        );
      }
    } catch (e) {
      // 4. Show error message if it fails
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text("❌ Connection Failed: $e"),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        decoration: const BoxDecoration(
          gradient: RadialGradient(
            colors: [Color(0xFF1A1A1A), Color(0xFF0D0D0D)],
            center: Alignment.center,
            radius: 1.0,
          ),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'NEON XOX',
              style: TextStyle(
                fontSize: 50,
                fontWeight: FontWeight.bold,
                color: Colors.cyanAccent,
                letterSpacing: 4,
                shadows: [
                  Shadow(blurRadius: 20, color: Colors.cyanAccent),
                ],
              ),
            ),
            const SizedBox(height: 50),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.transparent,
                side: const BorderSide(color: Colors.pinkAccent, width: 2),
                padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 15),
              ),
              onPressed: () => _pingFirebase(context),
              child: const Text(
                'PING FIREBASE',
                style: TextStyle(color: Colors.pinkAccent, fontSize: 18),
              ),
            ),
          ],
        ),
      ),
    );
  }
}