import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:provider/provider.dart';
import 'features/game/services/game_provider.dart';
import 'features/auth/screens/splash_screen.dart';
import 'firebase_options.dart'; // This file is generated by the FlutterFire CLI
import 'core/theme/theme.dart'; // Add this line at the top of main.dart

void main() async {
  // 1. Mandatory for async initialization in main()
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Initialize Mobile Ads SDK
  MobileAds.instance.initialize();

  runApp(
    // 4. Wrap the entire app in MultiProvider
    // This makes the GameProvider accessible to all screens (Menu, Game, etc.)
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => GameProvider()),
      ],
      child: const NeonXOXApp(),
    ),
  );
}

class NeonXOXApp extends StatelessWidget {
  const NeonXOXApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Neon XOX Multiplayer',
      debugShowCheckedModeBanner: false,
      
      // 5. Apply the custom Neon Dark Theme we created
      theme: AppTheme.darkTheme,
      
      // 6. Start at the Splash Screen to handle Auth/Initialization flow
      home: const SplashScreen(),
    );
  }
}